### ISSUE TITLE
Possibility to combine 2 fields to define a group

### ISSUE THREAD

**Issue by metabsd** [ServiceNowITOM/ansible-sn-inventory#7]
As an example.

sn_sys_class_name + used_for

A group name linux_server_production or linux_server_development.

Thank you!

**Comment by amittell** [comment]
I think it would be best to do with with a list unions and filters on the Ansible side, you would set groups = used_for, then in Ansible do an intersect of the items in the linux_server and the "production" or "development" lists.
e.g.

- set_fact: linux_server_production = {{ linux_server | intersect(production) }}
