### ISSUE TITLE
Possibility to modifiy the order.

### ISSUE THREAD

**Issue by metabsd** [ServiceNowITOM/ansible-sn-inventory#8]
We prefer to use the host_name instead of the ip_address.

Thank you in advance!

**Comment by metabsd** [comment]
For the moment I change that

`selection = ['ip_address', 'fqdn', 'host_name']`

**Comment by amittell** [comment]
I’ll add this as a config option when I get some time

**Comment by amittell** [comment]
Added support for this feature in 4cb773d40aaa92470d5e987d8825b5a5b5f3e864
